### ISSUE TITLE
Responsive problem in desktop

### ISSUE THREAD

**Issue by filhocf** [deciobenicio/kb-themeplus-stgray#11]
In a project with many columns, each one stay very small in its width. Take a look below.

![image](https://user-images.githubusercontent.com/952596/37964616-84485b38-3198-11e8-83b8-c8f85fcf0bc4.png)

And when expand the window.
![image](https://user-images.githubusercontent.com/952596/37964657-a82d9234-3198-11e8-94f9-cde90342fd32.png)

**Comment by rwfalcao** [comment]
This is how the board behaves on its compact view mode, you can enable horizontal scrolling by going to menu->Horizonatal Scrolling.
