### ISSUE TITLE
Text and Icons move while passing mouse pointer

### ISSUE THREAD

**Issue by eupolemo** [deciobenicio/kb-themeplus-stgray#4]
When using a Board on web version, while passing the mouse over the cards, the icons and text of the cards move and shade causing difficult to read, changing identation and moving the designated icon.
Without mouse over
![without_mouse](https://user-images.githubusercontent.com/15064935/36912519-b2b7abd0-1e25-11e8-8345-c7cc97d6b093.png)

With mouse over
![with_mouse](https://user-images.githubusercontent.com/15064935/36912513-ae37f132-1e25-11e8-9bd9-36b365def42f.png)

**Comment by TomNedry** [comment]
I don't know whether this effect is intended or not. To keep the space between colored border at the left and the content area, just alter the padding in the class ".task-board:hover"

from: "padding: 6px 8px 6px 0px;"
to: "padding: 6px 8px 6px 6px;"
